frase = 'Curso em Video Python'
novafrase = 'Que legal, mano brown'
print(frase[17:])
print(len(frase))
print(frase.count('o', 0, 13))
print(frase.find('Video'))
print(frase.find('android'))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.lstrip())
print(frase.rstrip())
print(frase.split())
print(' '.join(frase))
dividida = frase.split()
print(dividida)
print(dividida[2])
print(novafrase)
print(novafrase.replace('brown', 'blue'))
